- name: Traefik config
  become: true
  copy:
    src: files/traefik.toml
    dest: /etc/traefik.toml
- name: Traefik
  docker_container:
    image: "traefik"
    restart_policy: always
    name: "traefik"
    ports: "80:80,443:443"
    state: started
    command: --web --docker --docker.domain=piratenpartei.ch --logLevel=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/traefik.toml:/traefik.toml
      - /var/lib/traefik:/var/lib/traefik
