     - name: start mysql container
       docker_container:
         image: "mysql:5"
         name: "members-crm-mysql"
         state: started
         restart_policy: always
         pull: True
         volumes:
           - /data/mysql/members-crm:/var/lib/mysql
         env:
           MYSQL_ROOT_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/mysql/root:value') }}"
           MYSQL_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/members-crm/mysql/password:value') }}"
           MYSQL_USER="members-crm"
           MYSQL_DATABASE="members-crm"

     - name: start second mysql container
       docker_container:
         image: "mysql:5"
         name: "members-crm-mysql-civi"
         state: started
         pull: True
         restart_policy: always
         volumes:
           - /data/mysql/members-crm-civi:/var/lib/mysql
         env:
           MYSQL_ROOT_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/mysql/root:value') }}"
           MYSQL_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/members-crm/mysql/password:value') }}"
           MYSQL_USER="members-crm"
           MYSQL_DATABASE="members-crm-civi"

     - name: start civicrm container
       docker_container:
         image: wordpress:php5.6
         name: "members-crm"
         restart_policy: always
         labels:
          "traefik.enable": "true"
         state: started
         pull: True
         links:
           - members-crm-mysql:mysql
           - members-crm-mysql-civi:mysql-civi
         volumes:
           - /data/files/members-crm/:/var/www/html

     - name: start civicrm croncontainer
       docker_container:
         image: wordpress:php5.6
         name: "members-crm-cron"
         state: started
         pull: True
         restart_policy: always
         links:
           - members-crm-mysql:mysql
           - members-crm-mysql-civi:mysql-civi
         volumes:
           - /data/files/members-crm/:/var/www/html
         command: /var/www/html/startjobs.sh

     - name: start backup container for first mysql container
       docker_container:
         image: yloeffler/mysql-backup
         name: "members-crm-backup"
         state: started
         restart_policy: always
         pull: True
         links:
           - members-crm-mysql:mysql
         volumes:
           - /data/mysql-backup/members-crm/:/backup
         env:
           MYSQL_PASS="{{ lookup('hashi_vault', 'secret=secret/members-crm/mysql/password:value') }}"
           MAX_BACKUPS=3

     - name: start backup container for second mysql container
       docker_container:
         image: yloeffler/mysql-backup
         name: "members-crm-civi-backup"
         state: started
         restart_policy: always
         pull: True
         links:
           - members-crm-mysql-civi:mysql
         volumes:
           - /data/mysql-backup/members-crm-civi/:/backup
         env:
           MYSQL_PASS="{{ lookup('hashi_vault', 'secret=secret/members-crm/mysql/password:value') }}"
           MAX_BACKUPS=3
